name: Elm Make

run-name: Site is being built.

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: npm install elm
      - run: npx elm make src/Main.elm
